In [2]:
import numpy as np

In [3]:
k = 5

A = np.array(((0, 4, 3), (8, 0, k), (1, 1, 0)))

In [4]:
A

array([[0, 4, 3],
       [8, 0, 5],
       [1, 1, 0]])

In [5]:
def determinant(A):
    return A[0][0]*A[1][1] - A[0][1]*A[1][0]

In [6]:
A[:2, :2]

array([[0, 4],
       [8, 0]])

In [15]:
r = np.array(((0, 1), (1, 0))) #y = x
s = np.array(((1, 0), (0, -1))) #x-axis
t = np.array(((-1, 0), (0, 1))) #y-axis
A = np.array(((2, 5), (3, 4)))

In [13]:
A.dot(s)

array([[ 2, -5],
       [ 3, -4]])

In [14]:
A.dot(r)

array([[5, 2],
       [4, 3]])

In [17]:
A.dot(t)

array([[-2,  5],
       [-3,  4]])

In [20]:
A = np.array(((0,1,1), (1,1,1), (0,1,1)))
np.kron(A, A)

array([[0, 0, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 1, 1],
       [0, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 1, 1]])

In [24]:
B = np.block([[np.zeros((3,3)), A, A],
          [A, A, A],
          [np.zeros((3,3)), A, A]
         ]).astype(int)
B

array([[0, 0, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 1, 1],
       [0, 1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 1, 1]])