In [14]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [15]:
import numpy as np
import random

In [ ]:
# solve mab problem using only linear transformations

In [16]:
Q = np.zeros((5))
N = np.zeros((5))
R = [-1, 1, -2, 2, 0]

In [17]:
Q

array([0., 0., 0., 0., 0.])

In [18]:
for i in range(5):
    print(i)
    epsilon = random.random()
    if epsilon < 0.5:
        A = np.random.choice(np.arange(Q.size)) # pick a random arm if all Q values are equal
    else:
        A = np.argmax(Q) 
    reward = R[i]
    N[A] += 1
    Q[A] += (1/N[A])*(reward - Q[A])

0
1
2
3
4


In [19]:
#action 1 - rewards [-1]
#action 2 - rewards [1, -2, 2]
#action 3 - rewards [0]


In [20]:
Q

array([-1.,  0.,  1.,  0.,  0.])

In [21]:
A

1

In [22]:
N

array([1., 1., 1., 0., 2.])

In [1]:
# the reward for each action is the same
# set internal reward distribution/function
# plot reward curves

In [2]:
def bandit(action):
    return reward

In [4]:
# define reward function
# show how q-values change when reward function changes. Can we recreate an unknown reward function by looking at the outputs? What does 
# that look like? How does the original reward function get defined? Is it an equation, a pairing of inputs and outputs, or something else?