In [2]:
import pandas as pd
import numpy as np

In [3]:
#dynamic programming: given a number n, get pascal's triangle up to first n rows
#each number is the sum of the two numbers directly above it

#Pascal's matrix
#create df above without repeating rows, use for loop if needed

df = pd.DataFrame()

df['col1'] = [1, 1, 1, 1, 1]

for i in range(2, 6):
    df[f'col{i}'] = df[f'col{i-1}'].cumsum()

#create df without using for loop or list comprehension

[df[f'col{i-1}'].cumsum() for i in range(2,6)]

[0    1
 1    2
 2    3
 3    4
 4    5
 Name: col1, dtype: int64,
 0     1
 1     3
 2     6
 3    10
 4    15
 Name: col2, dtype: int64,
 0     1
 1     4
 2    10
 3    20
 4    35
 Name: col3, dtype: int64,
 0     1
 1     5
 2    15
 3    35
 4    70
 Name: col4, dtype: int64]

In [4]:
#change above to numpy
#create array without using for loop

In [5]:
#write a function that can calculate any binomial coefficient
#use numpy

In [6]:
df

col1  col2  col3  col4  col5
0     1     1     1     1     1
1     1     2     3     4     5
2     1     3     6    10    15
3     1     4    10    20    35
4     1     5    15    35    70

In [7]:
a = np.ones((5,5))
a 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
#get different matrices to overlay each other

In [46]:
a = np.tril(a)
b = np.pad(a,((0,0),(1,0)))[:, :-1]
c = np.pad(b,((0,0),(1,0)))[:, :-1]
d = np.pad(c,((0,0),(1,0)))[:, :-1]
e = np.pad(d,((0,0),(1,0)))[:, :-1]

In [53]:
a

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [54]:
b.cumsum(axis=0)

array([[0., 1., 0., 0., 0.],
       [0., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 4., 3., 2., 1.],
       [0., 5., 4., 3., 2.]])

In [55]:
c.cumsum(axis=0).cumsum(axis=0)

array([[ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  3.,  1.,  0.],
       [ 0.,  0.,  6.,  3.,  1.],
       [ 0.,  0., 10.,  6.,  3.],
       [ 0.,  0., 15., 10.,  6.]])

In [56]:
d.cumsum(axis=0).cumsum(axis=0).cumsum(axis=0)

array([[ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  1.],
       [ 0.,  0.,  0., 10.,  4.],
       [ 0.,  0.,  0., 20., 10.],
       [ 0.,  0.,  0., 35., 20.]])

In [57]:
e.cumsum(axis=0).cumsum(axis=0).cumsum(axis=0).cumsum(axis=0)

array([[ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  5.],
       [ 0.,  0.,  0.,  0., 15.],
       [ 0.,  0.,  0.,  0., 35.],
       [ 0.,  0.,  0.,  0., 70.]])

In [65]:
f = np.maximum(a, b.cumsum(axis=0))

In [68]:
g = np.maximum(f, c.cumsum(axis=0).cumsum(axis=0))

In [71]:
h = np.maximum(g, d.cumsum(axis=0).cumsum(axis=0).cumsum(axis=0))

In [77]:
np.maximum(h, e.cumsum(axis=0).cumsum(axis=0).cumsum(axis=0).cumsum(axis=0))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  3.,  6., 10., 15.],
       [ 1.,  4., 10., 20., 35.],
       [ 1.,  5., 15., 35., 70.]])

In [78]:
np.maximum(a, b.cumsum(axis=0), c.cumsum(axis=0).cumsum(axis=0))

array([[1., 1., 0., 0., 0.],
       [1., 2., 1., 0., 0.],
       [1., 3., 2., 1., 0.],
       [1., 4., 3., 2., 1.],
       [1., 5., 4., 3., 2.]])

In [ ]:
#generate binomial coefficent lower triangular matrix
#flip to get upper triangular
#multiply to get pascal as above