In [53]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import math

In [54]:
x = torch.linspace(-math.pi, math.pi, 2000)
y = torch.sin(x)
xx = x.unsqueeze(-1).pow(torch.tensor([1, 2, 3]))

In [55]:
model = torch.nn.Sequential(
    torch.nn.Linear(3, 10),
    torch.nn.Linear(10, 1),
    torch.nn.Flatten(0, 1)
)

loss_fn = torch.nn.MSELoss(reduction='sum')
lr = 1e-6

for t in range(2000):
    y_pred = model(xx)
    loss = loss_fn(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())
    
    model.zero_grad()
    loss.backward()
    
    with torch.no_grad():
        for param in model.parameters():
            param -= lr * param.grad

99 570.4019165039062
199 425.6173095703125
299 300.7923278808594
399 199.6876678466797
499 125.08256530761719
599 75.18798828125
699 44.679298400878906
799 27.367136001586914
899 18.1013126373291
999 13.354029655456543
1099 10.99708366394043
1199 9.852508544921875
1299 9.305039405822754
1399 9.045856475830078
1499 8.923992156982422
1599 8.866947174072266
1699 8.840336799621582
1799 8.827934265136719
1899 8.822175979614258
1999 8.819487571716309


In [56]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.0443,  0.1684,  0.0742],
                      [-0.2937,  0.4730,  0.1237],
                      [-0.2304,  0.5643, -0.1027],
                      [ 0.2968,  0.0717, -0.0231],
                      [-0.6672, -0.5220, -0.2895],
                      [-0.0086,  0.0084,  0.3166],
                      [-0.3721, -0.1921, -0.3604],
                      [-0.2502,  0.2719, -0.2709],
                      [ 0.4913, -0.2321, -0.0193],
                      [-0.5886,  0.3930,  0.3091]])),
             ('0.bias',
              tensor([-0.4629, -0.4709,  0.0522, -0.2512, -0.4871,  0.1533, -0.4036,  0.3017,
                      -0.3975, -0.0462])),
             ('1.weight',
              tensor([[ 0.0343,  0.0465,  0.0331,  0.1833, -0.4620, -0.1002,  0.0087,  0.0532,
                        0.4154, -0.5508]])),
             ('1.bias', tensor([0.0003]))])